/** 
 * generated by `__vorthApp` instance
 */
// @ts-check
/**
 * @typedef {'app'|'count'|'loop/child'|'loop/parent'|'multiref'|'test'} lifecyclesList
 */
/**
 * @template {lifecyclesList} T
  * @template {boolean} B
 * @param {T} lifecycleName
 * @param {B} [bypasWaitOnViewToRender]
 * @returns {`vorth='${T}${B extends true ? ';pre' : ''}'`}
 */
// @ts-expect-error
export const lifecycleAttr = (lifecycleName, bypasWaitOnViewToRender = false) => {
	const pre = bypasWaitOnViewToRender ? ';pre' : '';
	// @ts-expect-error
	return `vorth='${lifecycleName}${pre}'`;
};