/** 
 * generated by `__vorthApp` instance
 */
// @ts-check
/**
 * @typedef {'app'|'count'|'loop/child'|'loop/parent'|'multiref'|'test'} lifecyclesList
 */
/**
 * @template {lifecyclesList} T
 * @param {T} lifecycleName
 * @returns {`vorth='${T}'`}
 */
export const lifecycleAttr = (lifecycleName) => `vorth='${lifecycleName}'`;
