/** 
 * generated by `__vorthApp` instance
 */
// @ts-check
/**
 * @typedef {'log'|'log_'} libsList
 */
/**
 * @template {libsList} T
 * @callback importLib
 * @param {T} relativePath
 * - relativePath of lib inside `libs`;
 * @returns {Promise<T extends 'log_'?(options: { a: string, b: number })=>Promise<void>:T extends 'log'?(options:{a:string, b:number})=>Promise<void>:void>}
 */